language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_script:
  - mysql -e 'create database wp_slab_test;'
  - composer install -s dev
env:
  WP_DEBUG: true
  DB_NAME: wp_slab_test
  DB_USER: travis
  DB_PASSWORD: root
  DB_HOST: localhost
